services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/build
      - /app/node_modules
      - /app/.svelte-kit
    environment:
      NODE_ENV: production
      DATABASE_HOST: db
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: templateDB
      POSTGRES_PASSWORD: testpassword
    volumes:
      - ./src/db/database.sql:/docker-entrypoint-initdb.d/baseDB.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
